# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eb22b0c39bebf64606bcd6365e680a4de35ebe9d70dd64ec09acafcfd59eb6c106550fe4a957f32362f5cc854e1dbf0e458da153a566024a9fd1336b1082ffc2

test:
  secret_key_base: 0afa46538cb2c2266247282ffc6b8f5983a7f36e508fee589d03995c7b67663e36d30c75d19bc5d32f9a5feebe01ab61fa5f6750cc45100348f2f4fafa0913b1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
